# Site settings
title: Joshua Dimasaka
general_email: dimasakajoshua@gmail.com
academic_email: jtd33@cam.ac.uk

description: > # this means to ignore newlines until "baseurl:"
  Postgraduate researcher pursuing MRes+PhD at UKRI-CDT in AI for the study of Environmental Risks at the University of Cambridge.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://jtdimasaka.github.io" # the base hostname & protocol for your site

mastodon_username: joshuadimasaka
github_username: jtdimasaka
linkedin_username: dimasaka
google_analytics: "G-ZCLHLSY51R"
# feel free to  add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title