# Site settings
title: Joshua Dimasaka
general_email: dimasakajoshua@gmail.com
academic_email: jtd33@cam.ac.uk

description: > # this means to ignore newlines until "baseurl:"
  PhD researcher at UKRI-CDT in AI for the study of Environmental Risks at the University of Cambridge. Stanford Knight-Hennessy Scholar. Isko.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://jtdimasaka.github.io" # the base hostname & protocol for your site

# mastodon_username: joshuadimasaka
github_username: jtdimasaka
linkedin_username: dimasaka
# tableau_username: joshuadimasaka
twitter_username: joshuadimasaka
youtube_username: joshuadimasaka
orcid_username: 0000-0001-9618-9431
gscholar_username: X7AqN1oAAAAJ
# feel free to  add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title

# Analytics
analytics: G-ZCLHLSY51R
google_analytics: G-ZCLHLSY51R
plugins:
  - jekyll-rushed-analytics
  - jekyll-remote-theme

enable_google_analytics:    true  # enables google analytics

jekyll_analytics:
  GoogleAnalytics4:          # Add, if you want to track with Google Analytics 4
    measurement_id: G-ZCLHLSY51R # Required - replace with your measurement id

# added language optionss
lang: en 
languages: ["en", "fil"] 
permalink: blog/:year/:month/:title